language: objective-c
osx_image: xcode7.3
xcode_project: HHMACSwift.xcodeproj
xcode_scheme: HHMACSwift
xcode_sdk: iphonesimulator9.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap
after_success:
- bash <(curl -s https://codecov.io/bash) -J HHMacSwift